# https://github.com/NovaSoftworks/cs-uip-ui/charts/ui

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: user-identity-platform
  source:
    repoURL: https://github.com/NovaSoftworks/cs-uip-ui.git
    path: charts/ui/
    targetRevision: main
    helm:
      valuesObject:
        deployment:
          imagePullSecrets:
            - name: ghcr-auth
          env:
            - name: PUBLIC_BASE_URL
              value: https://account.novasoftworks.com
          readinessProbe:
            enabled: true
          livenessProbe:
            enabled: true

        ingress:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
