apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-identity-schema
  namespace: user-identity-platform
data:
  user.schema.json: |
    {
      "$id": "https://identity.novasoftworks.com/user.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "type": "string"
                },
                "last": {
                  "type": "string"
                }
              },
              "required": ["first"]
            }
          },
          "required": ["email", "name"],
          "additionalProperties": false
        }
      }
    }